# Site settings
title: "Jingyan Li"
description: "A quick website that showcases my background."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jingyan Li"
resume_title:                   "Student at Tsinghua University"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lijingya21@mails.tsinghua.edu.cn"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "a"
resume_contact_address:         "a"

resume_header_contact_info:     "lijingya21@mails.tsinghua.edu.cn"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a dedicated Industrial Engineering student at Tsinghua University with a strong academic record and hands-on research experience in virtual reality and user experience. My goal is to leverage my skills in data analysis and human factors to drive innovative solutions in technology and design.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            ""
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  #resume_facebook_url:         ""
  #resume_linkedin_url:          ""
  #resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://lijingyan.com"
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
